url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://citygabor.github.io/testpages" # the subpath of your site, e.g. /blog
title: "" # PowerShortcuts
markdown: kramdown
exclude: ['_sass', 'node_modules', 'assets', '_site', '.git']
